apiVersion: v1
kind: Service
metadata:
  name: microserviceb-service
spec:
  selector:
    app: microserviceb
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081   # ✅ must match Deployment
