apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicea-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicea
  template:
    metadata:
      labels:
        app: microservicea
    spec:
      containers:
        - name: microservicea
          image: harshdockerrtb/microservicea:1.0
          ports:
            - containerPort: 8080
          env:
            - name: MICROSERVICEB_URL
              value: "http://microserviceb-service:8080"
      imagePullSecrets:
        - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: microservicea-service
spec:
  selector:
    app: microservicea
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
